### ISSUE TITLE
[FEAT] Revision function added

### ISSUE THREAD

**Issue by r74tech** [r74tech/ftml-web#3]
**Is your feature request related to a problem? Please describe.**
I want to be able to leave Rev.

**Describe the solution you'd like**
We would like to use indexedDB and API to save the data locally and in Github Pages.

**Additional context**

Saving in Github Pages is done this way.
The advantage of doing this is that you can share the page with others.

The disadvantage is that the contents of the page will be made public, so it is necessary to delete them or add a confirmation message to the effect that there is no problem.
![image](https://user-images.githubusercontent.com/57354947/170096156-a8dbb990-ad9a-481c-b50c-65d67bf41c47.png)

**Comment by RTa-technology** [comment]
Save process implemented in GAS

**Comment by RTa-technology** [comment]
- [ ] revision display
- [ ] history acquisition with the same Id

**Comment by r74tech** [comment]
実装done
