### ISSUE TITLE
[FEAT] include構文をなにとぞ

### ISSUE THREAD

**Issue by iti119** [r74tech/ftml-web#5]
**問題点**
CSSテーマの改造をしたいのですが、元テーマのコードが長大かつ難解で難航しています

**解決策**
include構文による簡略化、可能であれば引数の使用ができるとはかどります。よろしくお願いします。

**Comment by RTa-technology** [comment]
現状の[ftml-wasm](https://www.npmjs.com/package/@vscode-ftml/ftml-wasm)ではincludeを解析していません．その為，独自手法でincludeを実装することになりそうです．
今考えている手法としては，github上にinclude元のftmlを置き，Wikitext内でfetchして，引数をregで代入した後にftml-wasmに通すという動作です．
ただ問題点として，
- {$xxx-{$yyyy}}のような形のinclude変数は代入できない可能性があること
- include内のincludeには対応できないこと

の2点が考えられます．

----
現状，繁忙期であるためすぐの対応はできませんがよろしくお願いいたします．

**Comment by Zokhoi** [comment]
After some discussion with @smlt, for now an idea would be to use either Crom's api to obtain the source of included pages on limited wikis, or Wikidot's `edit/TemplateSourceModule` ajax module for any page source on any wiki.

For these two routes, there are some options for precedence and fallback rules, either:
* serve the source by Wikidot ajax first for larger page source availability, and then fallback to Crom if Wikidot is down, or
* serve the source by Crom to not hit the Wikidot servers as hard, and then fall back to Wikidot when Crom does not have the source

**Comment by RTa-technology** [comment]
@Zokhoi, Well, thank you very much.
I will use the Crom API since I don't want to increase the number of requests to Wikidot.
I will think about the request method a little.

**Comment by Zokhoi** [comment]
Also, for the included pages, it would be good to implement some level of retrieved page source caching (and live preview keystroke debouncing as well) for higher speed and lower load

**Comment by RTa-technology** [comment]
Personally, I am wondering what to do when, for example, including a theme, etc., since recent ones often use "iftags" or include other themes internally.

If I don't consider the load on Wikidot, I could just use `edit/TemplateSourceModule` as you mentioned, but...

**Comment by RTa-technology** [comment]
> Also, for the included pages, it would be good to implement some level of retrieved page source caching (and live preview keystroke debouncing as well) for higher speed and lower load.

Indeed it is. I'll do my best to implement it.

**Comment by RTa-technology** [comment]
https://github.com/EoinDavey/tsPEG
https://github.com/metadevpro/ts-pegjs

**Comment by r74tech** [comment]
includeの実装done
